language: bash

matrix:
  include:
    - os: linux
    - os: osx

env:
  - SHELL=bash
  - NORE_TEST_DIR=$TRAVIS_BUILD_DIR/c

before_script:
  - git clone --depth=1 https://github.com/junjiemars/c.git
  - cd c
  - bash <(curl https://raw.githubusercontent.com/junjiemars/nore/master/bootstrap.sh)

script: 
  - $TRAVIS_BUILD_DIR/.travis-tests.sh
