language: generic
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - bash
      - build-essential
      - make
      - git
      - curl
script: >
  cd /tmp
  git clone --depth=1 https://github.com/junjiemars/c.git
  cd /tmp/c
  bash <(curl https://raws.githubusercontent.com/junjiemars/nore/master/bootstrap.sh)
  ./configure --has-hi
  make test
