language: bash

matrix:
  include:
    - os: linux
    - os: osx

env:
  - SHELL=bash
  - NORE_TEST_DIR=$TRAVIS_BUILD_DIR/nore_test

before_script:
  - mkdir -p $NORE_TEST_DIR
  - cd $NORE_TEST_DIR
  - bash <(curl https://raw.githubusercontent.com/junjiemars/nore/master/bootstrap.sh)

script: 
  - $TRAVIS_BUILD_DIR/.travis-tests.sh
