
math_objout := $(tmp_path)math$(nm_objext)
math_binout := $(bin_path)math$(nm_binext)

math: geo $(bin_path)math$(nm_binext)

math_cflags := $(CFLAGS) $(NM_INCS) -Og
math_ldflags := 


$(math_objout): $(src_path)math1.c
	$(CC) $(math_cflags) -c $^ $(nm_objout)$@


$(math_binout): $(math_objout) \
$(lib_path)libgeo.lib
	$(CC) $(CFLAGS) $(math_ldflags) $^ $(nm_binout)$@
