
math_objout := $(tmp_path)math$(obj_ext)
math_binout := $(bin_path)math$(bin_ext)

math: geo $(bin_path)math$(bin_ext)

math_cflags := $(CFLAGS) $(INC)


$(math_objout): $(src_path)math1.c
	$(CC) $(math_cflags) -c $^ $(obj_out)$@


$(math_binout): $(math_objout) $(lib_path)libgeo.lib
	$(CC) $(LFLAGS) $^ $(bin_out)$@

math_test: math
	PATH=$(lib_path):$PATH $(math_binout)
