name: Nore

on:
  pull_request:
    branches:
      - edge
  push:
    branches:
      - edge

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # checkout history and tags

      - name: Install Dependencies
        run: |
          sudo apt-get update
      - name: Test
        run: |
          CC=gcc ./test.sh
