name: Nore

on:
  pull_request:
    branches:
      - edge
  push:
    branches:
      - edge

jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - CC: "gcc"
          - CC: "clang"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # checkout history and tags

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang
      - name: Test Nore
        run: |
          CC=${{ matrix.CC }}./test.sh
